#spring.application.name=Gateway

spring:
  application:
    name: Gateway-service
  cloud:
    Gateway:
      mvc:
        routes:
          - id: PsApp
            uri: http://localhost:8081
            predicates:
              - Path=/api/usuarios/** #Revisar el nombre del endpoint
            filters:
              - StripPrefix=0


server:
  port: 8080
