#spring.application.name=App

spring:
  application:
    name: App
  datasource:
    url: jdbc:postgresql://localhost:5432/ps
    username: jonas24
    password: PracticaSupervisada123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        dll-auto: update

  # CONFIGURACIÓN DE MAIL (indentación correcta)
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuoficiopracticasupervisada@gmail.com
    password: Practicasupervisada0312
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

